apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jcrzx1i9c-go
  janus-idp.io/tekton: jcrzx1i9c-go
  backstage.io/kubernetes-id: jcrzx1i9c-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jcrzx1i9c-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
